version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    environment:
      KAFKA_KRAFT_MODE: true
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:${KAFKA_CONTROLLER_PORT}
      KAFKA_LISTENERS: PLAINTEXT://kafka:${KAFKA_LISTENER_PORT},CONTROLLER://kafka:${KAFKA_CONTROLLER_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:${KAFKA_LISTENER_PORT}
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
    volumes:
      - kafka_data:/var/lib/kafka/data
  kafka-setup:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - kafka
    entrypoint: [/bin/sh, -c]
    command: | 
      "
      kafka-topics --bootstrap-server kafka:${KAFKA_LISTENER_PORT} --list
      kafka-topics --bootstrap-server kafka:${KAFKA_LISTENER_PORT} --create --if-not-exists --topic ${TODO_EVENTS_KAFKA_TOPIC} --replication-factor 1 --partitions 1
      "
  kafka-ui:
    depends_on:
      - kafka
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "${KAFKA_UI_PORT}:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:${KAFKA_LISTENER_PORT}
  mongo:
    image: mongo:7.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes: 
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - todo_data:/data/db
  todoauth:
      build:
        context: ./
        dockerfile: ./todoauth/build/docker/Dockerfile
      ports:
        - "${TODO_AUTH_API_PORT}:8080"
      depends_on:
        - mongo
      environment: 
        - CONFIG_PRIVATEKEY=${PRIVATE_KEY}
        - CONFIG_PUBLICKEY=${PUBLIC_KEY}
        - CONFIG_TOKEN_ACCESSTOKENDURATION=20m
        - CONFIG_TOKEN_REFRESHTOKENDURATION=168h
        - CONFIG_MONGO_HOSTS=mongo:${MONGO_PORT}
        - CONFIG_MONGO_DATABASE=${MONGO_DATABASE}
        - CONFIG_MONGO_USERNAME=${MONGO_USERNAME}
        - CONFIG_MONGO_PASSWORD=${MONGO_PASSWORD}
        - CONFIG_MONGO_USETLS=false
        - CONFIG_HTTPAPI_PORT=8080
  todoprofile:
      build:
        context: ./
        dockerfile: ./todoprofile/build/docker/Dockerfile
      ports:
        - "${TODO_PROFILE_API_PORT}:8080"
      depends_on:
        - mongo
        - kafka
      environment: 
        - CONFIG_PUBLICKEY=${PUBLIC_KEY}
        - CONFIG_MONGO_HOSTS=mongo:${MONGO_PORT}
        - CONFIG_MONGO_DATABASE=${MONGO_DATABASE}
        - CONFIG_MONGO_USERNAME=${MONGO_USERNAME}
        - CONFIG_MONGO_PASSWORD=${MONGO_PASSWORD}
        - CONFIG_MONGO_USETLS=false
        - CONFIG_HTTPAPI_PORT=8080
  todo:
      build:
        context: ./
        dockerfile: ./todo/build/docker/Dockerfile
      ports:
        - "${TODO_API_PORT}:8080"
      depends_on:
        - mongo
        - kafka
        - kafka-setup
      environment: 
        - CONFIG_PUBLICKEY=${PUBLIC_KEY}
        - CONFIG_MONGO_HOSTS=mongo:${MONGO_PORT}
        - CONFIG_MONGO_DATABASE=${MONGO_DATABASE}
        - CONFIG_MONGO_USERNAME=${MONGO_USERNAME}
        - CONFIG_MONGO_PASSWORD=${MONGO_PASSWORD}
        - CONFIG_MONGO_USETLS=false
        - CONFIG_HTTPAPI_PORT=8080
        - CONFIG_KAFKA_BOOTSTRAPSERVERS=kafka:${KAFKA_LISTENER_PORT}
        - CONFIG_KAFKA_TODOEVENTSTOPIC=${TODO_EVENTS_KAFKA_TOPIC}
  todostatistic:
      build:
        context: ./
        dockerfile: ./todostatistic/build/docker/Dockerfile
      ports:
        - "${TODO_STATISTIC_API_PORT}:8080"
      depends_on:
        - mongo
        - kafka
        - kafka-setup
      environment: 
        - CONFIG_PUBLICKEY=${PUBLIC_KEY}
        - CONFIG_MONGO_HOSTS=mongo:${MONGO_PORT}
        - CONFIG_MONGO_DATABASE=${MONGO_DATABASE}
        - CONFIG_MONGO_USERNAME=${MONGO_USERNAME}
        - CONFIG_MONGO_PASSWORD=${MONGO_PASSWORD}
        - CONFIG_MONGO_USETLS=false
        - CONFIG_HTTPAPI_PORT=8080
        - CONFIG_CONSUMER_BOOTSTRAPSERVERS=kafka:${KAFKA_LISTENER_PORT}
        - CONFIG_CONSUMER_TODOEVENTSTOPIC=${TODO_EVENTS_KAFKA_TOPIC}
volumes: 
  kafka_data:
  todo_data: